version: "3.7"
services:
  app:
    build:
      args:
        user: aiv_dev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: short-link
    container_name: short-link-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - short-link

  db:
    image: mysql:5.7
    container_name: short-link-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - short-link

  nginx:
    image: nginx:alpine
    container_name: short-link-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - short-link

networks:
  short-link:
    driver: bridge
